import type { Metadata } from 'next'
import { Barlow, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const barlow = Barlow({ weight: ['500', '600'], subsets: ["vietnamese"] })

export const metadata: Metadata = {
  title: 'Home - Takup JSC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  )
}
